#!/bin/tcsh

#set DEFAULT_DESIGN = "btb"
#set DEFAULT_DESIGN = "decode_top"
#set DEFAULT_DESIGN = "br_pred_cnt"
#set DEFAULT_DESIGN = "fetch_top"
#set DEFAULT_DESIGN = "decoder"
#set DEFAULT_DESIGN = "cpu_pipeline"
#set DEFAULT_DESIGN = "rename"
#set DEFAULT_DESIGN = "rob_status"
#set DEFAULT_DESIGN = "exp_manage"
#set DEFAULT_DESIGN = "reorder_buffer"
#set DEFAULT_DESIGN = "inst_sched"
#set DEFAULT_DESIGN = "inst_queue"
#set DEFAULT_DESIGN = "alu_top"
#set DEFAULT_DESIGN = "br_status_buf"
set DEFAULT_DESIGN = "br_status"
#set DEFAULT_DESIGN = "fetch_iag"
